### ISSUE TITLE
Creating POI throws exception iOS

### ISSUE THREAD

**Issue by Lelelo1** [awesome7/XamAR#54] opened 2022-01-29 10:11 UTC
**Creating POI throws exception iOS**
This when I run the sample project. It is on this line in`MainPage.xaml.cs`

```
var obj = XamAR.World.Instance.AddPointOfInterest(location, title);
```

This is the exception when updating to newest version (0.2.28-alpha):

> 2022-01-29 11:08:44.594 CreatePOI.iOS[4970:1644982] 
Unhandled Exception:
DryIoc.ContainerException: code: Error.UnableToResolveUnknownService;
message: Unable to resolve resolution root XamAR.World
  from container without scope
Where no service registrations found
  and no dynamic registrations found in 0 of Rules.DynamicServiceProviders
  and nothing found in 0 of Rules.UnknownServiceResolvers
  at DryIoc.Throw.It (System.Int32 error, System.Object arg0, System.Object arg1, System.Object arg2, System.Object arg3) [0x00000] in /_/src/DryIoc/Container.cs:13642 
  at DryIoc.Container.TryThrowUnableToResolve (DryIoc.Request request) [0x0006d] in /_/src/DryIoc/Container.cs:1088 
  at DryIoc.Container.DryIoc.IContainer.ResolveFactory (DryIoc.Request request) [0x00072] in /_/src/DryIoc/Container.cs:1068 
  at DryIoc.Container.ResolveAndCache (System.Int32 serviceTypeHash, System.Type serviceType, DryIoc.IfUnresolved ifUnresolved) [0x00021] in /_/src/DryIoc/Container.cs:367 
  at DryIoc.Container.DryIoc.IResolver.Resolve (System.Type serviceType, DryIoc.IfUnresolved ifUnresolved) [0x0011c] in /_/src/DryIoc/Container.cs:356 
  at DryIoc.Resolver.Resolve[TService] (DryIoc.IResolver resolver, DryIoc.IfUnresolved ifUnresolved) [0x00000] in <203409f731464ce59f95fa77aa300dd7>:0 
  at XamAR.World.get_Instance () [0x00006] in <f71f7f888c674124acd730d47750a1bb>:0 
  at CreatePOI.MainPage.OnAppearing () [0x0002f] in /Users/lelelo1/Projects/XamAR/samples/CreatePOI/CreatePOI/CreatePOI/MainPage.xaml.cs:29 
  at Xamarin.Forms.Page.SendAppearing () [0x00045] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:452 
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidAppear (System.Boolean animated) [0x0004d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:215 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:73 
  at CreatePOI.iOS.Application.Main (System.String[] args) [0x00001] in /Users/lelelo1/Projects/XamAR/samples/CreatePOI/CreatePOI/CreatePOI.iOS/Main.cs:17 
2022-01-29 11:08:44.597 CreatePOI.iOS[4970:1644982] Unhandled managed exception: code: Error.UnableToResolveUnknownService;
message: Unable to resolve resolution root XamAR.World
  from container without scope
Where no service registrations found
  and no dynamic registrations found in 0 of Rules.DynamicServiceProviders
  and nothing found in 0 of Rules.UnknownServiceResolvers (DryIoc.ContainerException)
  at DryIoc.Throw.It (System.Int32 error, System.Object arg0, System.Object arg1, System.Object arg2, System.Object arg3) [0x00000] in /_/src/DryIoc/Container.cs:13642 
  at DryIoc.Container.TryThrowUnableToResolve (DryIoc.Request request) [0x0006d] in /_/src/DryIoc/Container.cs:1088 
  at DryIoc.Container.DryIoc.IContainer.ResolveFactory (DryIoc.Request request) [0x00072] in /_/src/DryIoc/Container.cs:1068 
  at DryIoc.Container.ResolveAndCache (System.Int32 serviceTypeHash, System.Type serviceType, DryIoc.IfUnresolved ifUnresolved) [0x00021] in /_/src/DryIoc/Container.cs:367 
  at DryIoc.Container.DryIoc.IResolver.Resolve (System.Type serviceType, DryIoc.IfUnresolved ifUnresolved) [0x0011c] in /_/src/DryIoc/Container.cs:356 
  at DryIoc.Resolver.Resolve[TService] (DryIoc.IResolver resolver, DryIoc.IfUnresolved ifUnresolved) [0x00000] in <203409f731464ce59f95fa77aa300dd7>:0 
  at XamAR.World.get_Instance () [0x00006] in <f71f7f888c674124acd730d47750a1bb>:0 
  at CreatePOI.MainPage.OnAppearing () [0x0002f] in /Users/lelelo1/Projects/XamAR/samples/CreatePOI/CreatePOI/CreatePOI/MainPage.xaml.cs:29 
  at Xamarin.Forms.Page.SendAppearing () [0x00045] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:452 
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidAppear (System.Boolean animated) [0x0004d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:215 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:73 
  at CreatePOI.iOS.Application.Main (System.String[] args) [0x00001] in /Users/lelelo1/Projects/XamAR/samples/CreatePOI/CreatePOI/CreatePOI.iOS/Main.cs:17 

=================================================================
	Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x108ea7b30 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108e9e5ac - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108ea7078 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x1f2177c10 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1f2185378 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x18c66cf50 - /usr/lib/system/libsystem_c.dylib : abort
	0x109030878 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : xamarin_find_protocol_wrapper_type
	0x108f00758 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x108e9e1f0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108e9cbc4 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108e9365c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x105680f5c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108c376cc - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108bb2d58 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108bb27bc - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108bad1a0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108bacf90 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108c00c1c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108e7da8c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108a6320c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x107e9c5ac - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x1079eea2c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x1055c35e0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108eae8ac - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x108f5b2d4 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x108f5e758 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x104c930ec - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x104cf708c - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x183d63cac - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x184557fc0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183e864d8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x18171de18 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1817a46f0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x183d63e74 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183e50ce0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183dd2764 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183dec388 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183ee32d4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183df48f8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183d1d278 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183d1d990 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183d1db40 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x181751610 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1817208f4 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x18171b98c - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x18172f468 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x19d2ba38c - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x1840d1088 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x183e4f958 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x106793c18 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x106071480 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x104d1ede0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x1055c35e0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x108eae8ac - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x108f5b2d4 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x108f60548 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : mono_pmip
	0x108e931a0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x10903f2a8 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : xamarin_get_original_working_directory_path
	0x104d1ece0 - /private/var/containers/Bundle/Application/45B3B52D-2211-46C7-A8D1-E72F4C1CF832/CreatePOI.iOS.app/CreatePOI.iOS : 
	0x109971aa4 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1b8ce3964):0x1b8ce3954  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1b8ce3964  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x1b8ce3974  34 ee ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  4........{...._.
0x1b8ce3984  c0 03 5f d6 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  .._..#...{......

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================

**Comment by miki-bgd** [comment] 2022-02-01 20:21
Hello, thank you for your feedback.

Sorry for delay, we are currently busy (with other development), so please give us some days and we'll get back to this issue.

PS. You said "This is the exception when updating to newest version (0.2.28-alpha)". Have you tried some previous version where it worked?

**Comment by Lelelo1** [comment] 2022-02-02 16:03
No it did not work on previous versions either

**Comment by miki-bgd** [comment] 2022-02-07 21:34
Hello, thank you for your patience.

I have created small test app, but i was unable to reproduce the bug you reported.
Few things you should check:
1. In **AppDelegate.cs** file add following line:
`// Add this line here
XamAR.WorldForms.Init();

global::Xamarin.Forms.Forms.Init();
LoadApplication(new App());`

2. In **Info.plist** permissions are added:
`<key>NSCameraUsageDescription</key>
	<string>bla</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>New Entry</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>New Entry</string>
	<key>NSLocationUsageDescription</key>
	<string>New Entry</string>
	<key>NSMotionUsageDescription</key>
	<string>New Entry</string>`
It is copied from here:
https://github.com/awesome7/XamAR/tree/main/samples/BasicSample


If you continue to have the same issue, please zip and upload complete solution so i can take a look.

Regards

**Comment by Lelelo1** [comment] 2022-02-20 09:57
Thanks it's working.

```
XamAR.WorldForms.Init();
```

Was missing in the sample

**Comment by miki-bgd** [comment] 2022-02-20 18:13
@Lelelo1 Great it works! Samples do need some updates, thanks for the feedback!

PS. I will close this issue, but if you have any question or comment, feel free to post or open new one.

**Closed as completed by miki-bgd** 2022-02-20 18:13 UTC
